#application: phantomtype-180814
#version: 1
runtime: go
api_version: go1

handlers:
- url: /hello
  script: _go_app
- url: /prepare
  script: _go_app
- url: /photo
  script: _go_app

- url: /(.*\.css)
  mime_type: text/css
  static_files: dist/\1
  upload: dist/(.*\.css)

- url: /(.*\.html)
  mime_type: text/html
  static_files: dist/\1
  upload: dist/(.*\.html)

- url: /(.*\.ico)
  mime_type: image/x-icon
  static_files: dist/\1
  upload: dist/(.*\.ico)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: dist/\1
  upload: dist/(.*\.js)

- url: /(.*\.ttf)
  mime_type: font/truetype
  static_files: dist/\1
  upload: dist/(.*\.ttf)

- url: /(.*\.woff)
  mime_type: application/x-font-woff
  static_files: dist/\1
  upload: dist/(.*\.woff)

- url: /(.*\.xml)
  mime_type: application/xml
  static_files: dist/\1
  upload: dist/(.*\.xml)

- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png|svg))
  static_files: dist/\1
  upload: dist/(.*\.(bmp|gif|ico|jpeg|jpg|png|svg))

- url: /(.+)/
  static_files: dist/\1/index.html
  upload: dist/(.+)/index.html

- url: /
  static_files: dist/index.html
  upload: dist/index.html

skip_files:
  - ^\.idea/.*
  - ^\.git/.*
  - ^\.github/.*
  - ^\.next/.*
  - ^node_modules/(.*/)?
  - ^build/.*
  - ^components/.*
  - ^pages/.*
  - ^exif_parse_dev/.*
  - ^tmp/.*
  - ^types/.*

